import settings

SCALE_FACTOR = 6
ITEMS_SCALE_FACTOR = 5
UI_SCALE_FACTOR = 2

FACING_EAST = 0
FACING_WEST = 1

OLD_MAN = (98, 224, 12, 16)
PIRATE = (113, 224, 14, 16)
RED_WIZARD = (128, 224, 15, 16)
PURPLE_WIZARD = (144, 224, 15, 16)

CHARACTERS_DICT = {
    'OLD_MAN': OLD_MAN,
    'PIRATE': PIRATE,
    'RED_WIZARD': RED_WIZARD,
    'PURPLE_WIZARD': PURPLE_WIZARD,
}

CHARACTERS = [
    'OLD_MAN',
    'PIRATE',
    'RED_WIZARD',
    'PURPLE_WIZARD',
]

SMALL_BLOOD_CRYING_MOB = (3, 150, 9, 10)
BLOOD_CRYING_MOB = (36, 144, 8, 16)
ROTTEN_BLOOD_CRYING_MOB = (52, 144, 8, 16)
SMALL_TROLL_MOB = (34, 160, 11, 16)
BIG_TROLL_MOB = (102, 182, 20, 26)


MOBS_DICT = {
    'SMALL_BLOOD_CRYING_MOB': SMALL_BLOOD_CRYING_MOB,
    'BLOOD_CRYING_MOB': BLOOD_CRYING_MOB,
    'ROTTEN_BLOOD_CRYING_MOB': ROTTEN_BLOOD_CRYING_MOB,
    'SMALL_TROLL_MOB': SMALL_TROLL_MOB,
    'BIG_TROLL_MOB': BIG_TROLL_MOB,
}

MOBS = [
    'BLOOD_CRYING_MOB'
]

GREEN_LIQUID_ITEM = (133, 212, 7, 11)
WIDE_GREEN_LIQUID_ITEM = (196, 196, 9, 11)
WIDE_RED_LIQUID_ITEM = (196, 180, 9, 11)
WIDE_BLUE_LIQUID_ITEM = (196, 212, 9, 11)

# Weapons
BASIC_SWORD = (179, 10, 10, 21)

# Backgrounds
FLOOR_BACKGROUND = (0, 91, 64, 48)
WALL_BACKGROUND = (1, 12, 46, 25)
WALL_FRONT_BACKGROUND = (1, 12, 46, 7)

# UI
# Corners
UI_BOX_CORNER_TOP_LEFT = (64, 41, 6, 7)
UI_BOX_CORNER_BOTTOM_LEFT = (64, 56, 8, 7)
UI_BOX_CORNER_BOTTOM_RIGHT = (96, 56, 8, 7)
UI_BOX_CORNER_TOP_RIGHT = (98, 41, 6, 7)
# Horizontal bars
UI_BOX_TOP_HORIZONTAL_BAR = (71, 41, 1, 6)
UI_BOX_BOTTOM_HORIZONTAL_BAR = (74, 58, 1, 5)
# Vertical bars
UI_BOX_VERTICAL_BAR_LEFT = (64, 48, 6, 1)
UI_BOX_VERTICAL_BAR_RIGHT = (98, 48, 6, 1)
# Background
UI_BOX_BACKGROUND = (80, 104, 24, 24)
UI_BOX_BACKGROUND_COLOR_PAPYRUS = (211, 191, 169)
UI_BOX_TEXT_COLOR_PAPYRUS = (71, 58, 57)

# Sprites
SPRITES_UI_PATH = "./assets/sprites/sprites_ui.png"

# Sound
BACKGROUND_SOUND = "./assets/sounds/background/Guitar-Mayhem-6" + settings.AUDIO_EXTENSION
ENDING_SOUND = "assets/sounds/ending" + settings.AUDIO_EXTENSION
MAIN_MENU_SOUND = "assets/sounds/main_menu" + settings.AUDIO_EXTENSION

# SFX
BOTTLE_PICKED_SFX = "assets/sounds/sfx/bottle_picked.wav"
PLAYER_KILLED_SFX = "assets/sounds/sfx/kill.wav"
WALL_HIT_SFX = "assets/sounds/sfx/boundary_hit.wav"
MENU_ITEM_CHANGED_SFX = "./assets/sounds/sfx/menu_item_changed.wav"
